name: Terraform Validation

on:
  push:
    branches:
      - infra_features  # Trigger on pushes to the infra_features branch
  pull_request:
    branches:
      - infra_features  # Optionally, trigger on pull requests targeting infra_features
#  workflow_dispatch:  # Allow manual trigger

jobs:
  validate:
    runs-on: ubuntu-latest


    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      # Step 1: Checkout Repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Setup Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0

      #Step 1: Change to Terraform Directory
      - name: Change to Terraform Directory
        working-directory: ./terraform
        run: pwd     
      
      # Step 3: Initialize Terraform
      - name: Terraform Init
        run: terraform init
      
      # Step 3: Initialize Terraform
      #- name: Terraform Init
      #  run: |
      #        cd terraform
      #        terraform init


      # Step 4: Validate Terraform
      - name: Terraform Validate
        run: terraform validate
